function createfigure(cdata1, XData1, YData1, XData2, YData2, cdata2, YData3, YData4, cdata3, cdata4, cdata5, cdata6)
%CREATEFIGURE(CDATA1, XDATA1, YDATA1, XDATA2, YDATA2, CDATA2, YDATA3, YDATA4, CDATA3, CDATA4, CDATA5, CDATA6)
%  CDATA1:  image cdata
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  XDATA2:  line xdata
%  YDATA2:  line ydata
%  CDATA2:  image cdata
%  YDATA3:  line ydata
%  YDATA4:  line ydata
%  CDATA3:  image cdata
%  CDATA4:  image cdata
%  CDATA5:  image cdata
%  CDATA6:  image cdata

%  Auto-generated by MATLAB on 08-Apr-2020 12:36:10

% Create figure
figure1 = figure('InvertHardcopy','off','PaperUnits','normalized',...
    'PaperType','A4',...
    'Tag','Graphics',...
    'Name','SPM12 (7771): Graphics',...
    'Color',[1 1 1]);
colormap(gray);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.206732551157223 0.495581950729009 0.242822203714212 0.228524008817062]);
hold(axes1,'on');

% Create image
image(cdata1,'Parent',axes1,'HitTest','off','Tag','Transverse');

% Create line
line(XData1,YData1,'Parent',axes1,'HitTest','off','Color',[0 0 1]);

% Create line
line(XData2,YData2,'Parent',axes1,'HitTest','off','Color',[0 0 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.5 244.091806515723]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.5 330.772967078231]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'Layer','top','XTick',[],'YTick',[]);
% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.206732551157223 0.732990362980648 0.242822203714212 0.21569616291176]);
hold(axes2,'on');

% Create image
image(cdata2,'Parent',axes2,'HitTest','off','Tag','Transverse');

% Create line
line(XData1,YData3,'Parent',axes2,'HitTest','off','Color',[0 0 1]);

% Create line
line(XData2,YData4,'Parent',axes2,'HitTest','off','Color',[0 0 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0.5 244.091806515723]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0.5 312.233598937888]);
box(axes2,'on');
% Set the remaining axes properties
set(axes2,'Layer','top','XTick',[],'YTick',[]);
% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.460995789030278 0.732990362980648 0.329229504227971 0.21569616291176]);
hold(axes3,'on');

% Create image
image(cdata3,'Parent',axes3,'HitTest','off','Tag','Transverse');

% Create line
line(YData2,YData3,'Parent',axes3,'HitTest','off','Color',[0 0 1]);

% Create line
line(YData1,YData4,'Parent',axes3,'HitTest','off','Color',[0 0 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0.5 330.772967078231]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[0.5 312.233598937888]);
box(axes3,'on');
% Set the remaining axes properties
set(axes3,'Layer','top','XTick',[],'YTick',[]);
% Create axes
axes4 = axes('Parent',figure1,...
    'Position',[0.206732551157223 0.0135558069381599 0.242822203714212 0.228524008817062]);
hold(axes4,'on');

% Create image
image(cdata4,'Parent',axes4,'HitTest','off','Tag','Transverse');

% Create line
line(XData1,YData1,'Parent',axes4,'HitTest','off','Color',[0 0 1]);

% Create line
line(XData2,YData2,'Parent',axes4,'HitTest','off','Color',[0 0 1]);

% Create contour
contour(cdata1,'HitTest','off','Parent',axes4,'LineColor',[1 0 0],...
    'LevelList',[15.9959650458896 30.6509157045419 45.3058663631943]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes4,[0.5 244.091806515723]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes4,[0.5 330.772967078231]);
box(axes4,'on');
% Set the remaining axes properties
set(axes4,'Layer','top','XTick',[],'YTick',[]);
% Create axes
axes5 = axes('Parent',figure1,...
    'Position',[0.206732551157223 0.250964219189799 0.242822203714212 0.21569616291176]);
hold(axes5,'on');

% Create image
image(cdata5,'Parent',axes5,'HitTest','off','Tag','Transverse');

% Create line
line(XData1,YData3,'Parent',axes5,'HitTest','off','Color',[0 0 1]);

% Create line
line(XData2,YData4,'Parent',axes5,'HitTest','off','Color',[0 0 1]);

% Create contour
contour(cdata2,'HitTest','off','Parent',axes5,'LineColor',[1 0 0],...
    'LevelList',[14.9344875010759 28.812910001737 42.6913325023981]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes5,[0.5 244.091806515723]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes5,[0.5 312.233598937888]);
box(axes5,'on');
% Set the remaining axes properties
set(axes5,'Layer','top','XTick',[],'YTick',[]);
% Create axes
axes6 = axes('Parent',figure1,...
    'Position',[0.460995789030278 0.250964219189799 0.329229504227971 0.21569616291176]);
hold(axes6,'on');

% Create image
image(cdata6,'Parent',axes6,'HitTest','off','Tag','Transverse');

% Create line
line(YData2,YData3,'Parent',axes6,'HitTest','off','Color',[0 0 1]);

% Create line
line(YData1,YData4,'Parent',axes6,'HitTest','off','Color',[0 0 1]);

% Create contour
contour(cdata3,'HitTest','off','Parent',axes6,'LineColor',[1 0 0],...
    'LevelList',[16 32 48]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes6,[0.5 330.772967078231]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes6,[0.5 312.233598937888]);
box(axes6,'on');
% Set the remaining axes properties
set(axes6,'Layer','top','XTick',[],'YTick',[]);
