
  spm_check_registration('G:\lemo_preproc\fbl_a\gpl001\anat\wimGPL001_T1w.nii',...
         'G:\lemo_preproc\fbl_a\gpl001\func\run1\s6wmeanuaGPL001_fbl_a_block1_bold.nii',...
         'G:\lemo_preproc\fbl_a\gpl001\func\run2\s6wmeanuaGPL001_fbl_a_block2_bold.nii',...
          'G:\lemo_preproc\fbl_b\gpl001\func\run1\s6wmeanuaGPL001_fbl_b_block1_bold.nii',...
          'G:\lemo_preproc\fbl_b\gpl001\func\run2\s6wmeanuaGPL001_fbl_b_block2_bold.nii')
 
 

  spm_check_registration('G:\lemo_preproc\fbl_a\gpl002\anat\wimGPL002_T1w.nii',...
         'G:\lemo_preproc\fbl_a\gpl002\func\run1\s6wmeanuaGPL002_fbl_a_block1_bold.nii',...
         'G:\lemo_preproc\fbl_a\gpl002\func\run2\s6wmeanuaGPL002_fbl_a_block2_bold.nii',...
          'G:\lemo_preproc\fbl_b\gpl002\func\run1\s6wmeanuaGPL002_fbl_b_block1_bold.nii',...
          'G:\lemo_preproc\fbl_b\gpl002\func\run2\s6wmeanuaGPL002_fbl_b_block2_bold.nii')
 


spm_check_registration('G:\lemo_preproc\fbl_a\gpl003\anat\wimGPL003_T1w.nii',...
         'G:\lemo_preproc\fbl_a\gpl003\func\run1\s6wmeanuaGPL003_fbl_a_block1_bold.nii',...
         'G:\lemo_preproc\fbl_a\gpl003\func\run2\s6wmeanuaGPL003_fbl_a_block2_bold.nii',...
          'G:\lemo_preproc\fbl_b\gpl003\func\run1\s6wmeanuaGPL003_fbl_b_block1_bold.nii',...
          'G:\lemo_preproc\fbl_b\gpl003\func\run2\s6wmeanuaGPL003_fbl_b_block2_bold.nii')
 
 
